/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChildCalendar: typeof import('./src/components/calendar/ChildCalendar.vue')['default']
    ChildTabBar: typeof import('./src/components/ChildTabBar.vue')['default']
    CoinDisplay: typeof import('./src/components/coins/CoinDisplay.vue')['default']
    CopperCoin: typeof import('./src/components/coins/CopperCoin.vue')['default']
    DrawAnimation: typeof import('./src/components/blindBox/DrawAnimation.vue')['default']
    DrawHistoryList: typeof import('./src/components/blindBox/DrawHistoryList.vue')['default']
    GiftCard: typeof import('./src/components/blindBox/GiftCard.vue')['default']
    GoldenCoin: typeof import('./src/components/coins/GoldenCoin.vue')['default']
    MilestoneCelebration: typeof import('./src/components/MilestoneCelebration.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SilverCoin: typeof import('./src/components/coins/SilverCoin.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
  }
}
