/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllocationPieChart: typeof import('./src/components/charts/AllocationPieChart.vue')['default']
    AppTabBar: typeof import('./src/components/common/AppTabBar.vue')['default']
    AssetCard: typeof import('./src/components/asset/AssetCard.vue')['default']
    AssetForm: typeof import('./src/components/asset/AssetForm.vue')['default']
    AssetListItem: typeof import('./src/components/asset/AssetListItem.vue')['default']
    CategoryGrid: typeof import('./src/components/asset/CategoryGrid.vue')['default']
    CurrencyButton: typeof import('./src/components/common/CurrencyButton.vue')['default']
    CurrencyPicker: typeof import('./src/components/common/CurrencyPicker.vue')['default']
    CurrencySelector: typeof import('./src/components/common/CurrencySelector.vue')['default']
    DailyCostChart: typeof import('./src/components/charts/DailyCostChart.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    LiabilityCard: typeof import('./src/components/liability/LiabilityCard.vue')['default']
    LiabilityForm: typeof import('./src/components/liability/LiabilityForm.vue')['default']
    MemberCard: typeof import('./src/components/family/MemberCard.vue')['default']
    MoneyDisplay: typeof import('./src/components/common/MoneyDisplay.vue')['default']
    NetWorthCard: typeof import('./src/components/dashboard/NetWorthCard.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusSummaryGrid: typeof import('./src/components/dashboard/StatusSummaryGrid.vue')['default']
    TagSelector: typeof import('./src/components/asset/TagSelector.vue')['default']
    TrendLineChart: typeof import('./src/components/charts/TrendLineChart.vue')['default']
    UsageFreqSelector: typeof import('./src/components/asset/UsageFreqSelector.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
