/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertCards: typeof import('./src/components/dashboard/AlertCards.vue')['default']
    AllocationPieChart: typeof import('./src/components/charts/AllocationPieChart.vue')['default']
    AppTabBar: typeof import('./src/components/common/AppTabBar.vue')['default']
    AssetCard: typeof import('./src/components/asset/AssetCard.vue')['default']
    AssetForm: typeof import('./src/components/asset/AssetForm.vue')['default']
    AssetListItem: typeof import('./src/components/asset/AssetListItem.vue')['default']
    CategoryGrid: typeof import('./src/components/asset/CategoryGrid.vue')['default']
    CurrencyButton: typeof import('./src/components/common/CurrencyButton.vue')['default']
    CurrencyPicker: typeof import('./src/components/common/CurrencyPicker.vue')['default']
    CurrencySelector: typeof import('./src/components/common/CurrencySelector.vue')['default']
    DailyCostChart: typeof import('./src/components/charts/DailyCostChart.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    LiabilityCard: typeof import('./src/components/liability/LiabilityCard.vue')['default']
    LiabilityForm: typeof import('./src/components/liability/LiabilityForm.vue')['default']
    MemberCard: typeof import('./src/components/family/MemberCard.vue')['default']
    MoneyDisplay: typeof import('./src/components/common/MoneyDisplay.vue')['default']
    NetWorthCard: typeof import('./src/components/dashboard/NetWorthCard.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusSummaryGrid: typeof import('./src/components/dashboard/StatusSummaryGrid.vue')['default']
    TagSelector: typeof import('./src/components/asset/TagSelector.vue')['default']
    TrendLineChart: typeof import('./src/components/charts/TrendLineChart.vue')['default']
    UsageFreqSelector: typeof import('./src/components/asset/UsageFreqSelector.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
  }
}
