packages:
  - 'frontend/apps/*'
  - 'frontend/packages/*'
  - '!**/node_modules/**'
allowBuilds:
  core-js: false
  esbuild: set this to true or false
  sharp: set this to true or false
patchedDependencies:
  vue-router@4.6.4: patches/vue-router@4.6.4.patch
