"""Child device binding token model for family association on independent devices."""

from datetime import datetime

from sqlalchemy import BigInteger, Boolean, DateTime, ForeignKey, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.utils.snowflake import next_id


class ChildBindToken(Base):
    """Single-use token for binding a child device to a family.

    Generated by parent (owner role), shared via URL link.
    Consumed on first use to associate child device with family_id.
    """

    __tablename__ = "child_bind_tokens"

    id: Mapped[int] = mapped_column(
        BigInteger, primary_key=True, default=next_id
    )
    family_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("families.id"), nullable=False
    )
    token: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    used: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    family = relationship("Family", back_populates="child_bind_tokens")
