"""Add custom_title to Family

Revision ID: d9f505ab1696
Revises: fffd4c754ec1
Create Date: 2026-03-23 17:07:05.617632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f505ab1696'
down_revision: Union[str, None] = 'fffd4c754ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('custom_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'custom_title')
    # ### end Alembic commands ###