"""add user settings fields and asset extended fields

Revision ID: fffd4c754ec1
Revises: 50672c82a858
Create Date: 2026-03-22 09:50:44.165436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fffd4c754ec1'
down_revision: Union[str, None] = '50672c82a858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: The drop_table commands were removed as these tables exist in models
    # Only keeping the user settings field changes
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###