"""Tests for run_extras.sync_title_from_checkpoint — checkpoint→session sync.

Regression guard: the thread title is generated by DeerFlow's
``TitleMiddleware`` (already active in the chat path via ``_build_middlewares``)
and written to the LangGraph checkpoint's ``channel_values["title"]``. This
function must read that title and persist it to the ``ai_chat_sessions`` record
the frontend reads via ``getThread`` — replacing the old
``generate_and_save_title`` which made a redundant second LLM call and was
bugged on the ai_config envelope / base_url key shape.
"""

from types import SimpleNamespace
from unittest.mock import AsyncMock, patch

from apps.agent.services.runtime.run_extras import sync_title_from_checkpoint


def _checkpoint_with_title(title: str | None) -> SimpleNamespace:
    """Build a fake CheckpointTuple whose .checkpoint.channel_values has title."""
    return SimpleNamespace(checkpoint={"channel_values": {"title": title}})


async def test_sync_title_from_checkpoint_persists_title_from_checkpoint():
    """The checkpoint title is persisted to the session row."""
    with (
        patch(
            "apps.agent.services.deerflow_adapter.family_adapter_cache._get_shared_checkpointer"
        ) as mock_get_ckpt,
        patch("apps.agent.services.session_store.AiSessionRepository") as MockRepo,
    ):
        checkpointer = mock_get_ckpt.return_value
        checkpointer.aget_tuple = AsyncMock(
            return_value=_checkpoint_with_title("家庭资产总览")
        )

        repo = MockRepo.return_value
        repo.get_session = AsyncMock(return_value={"title": None})
        repo.update_summary = AsyncMock()

        await sync_title_from_checkpoint("thread-1", "family-1")

    # The checkpoint title is persisted via the session repo — proves the
    # sync reads from channel_values["title"] and writes to the session row.
    repo.update_summary.assert_awaited_once()
    kwargs = repo.update_summary.call_args.kwargs
    assert kwargs["session_id"] == "thread-1"
    assert kwargs["family_id"] == "family-1"
    assert kwargs["title"] == "家庭资产总览"


async def test_sync_title_skips_when_no_checkpoint():
    """No save when the checkpoint doesn't exist (stream never ran)."""
    with (
        patch(
            "apps.agent.services.deerflow_adapter.family_adapter_cache._get_shared_checkpointer"
        ) as mock_get_ckpt,
        patch("apps.agent.services.session_store.AiSessionRepository") as MockRepo,
    ):
        checkpointer = mock_get_ckpt.return_value
        checkpointer.aget_tuple = AsyncMock(return_value=None)

        await sync_title_from_checkpoint("thread-1", "family-1")

    MockRepo.return_value.update_summary.assert_not_called()


async def test_sync_title_skips_when_checkpoint_has_no_title():
    """No save when the checkpoint exists but title is unset (middleware didn't run)."""
    with (
        patch(
            "apps.agent.services.deerflow_adapter.family_adapter_cache._get_shared_checkpointer"
        ) as mock_get_ckpt,
        patch("apps.agent.services.session_store.AiSessionRepository") as MockRepo,
    ):
        checkpointer = mock_get_ckpt.return_value
        checkpointer.aget_tuple = AsyncMock(return_value=_checkpoint_with_title(None))

        await sync_title_from_checkpoint("thread-1", "family-1")

    MockRepo.return_value.update_summary.assert_not_called()


async def test_sync_title_skips_when_session_already_titled():
    """An existing non-default title is not overwritten (user may have renamed)."""
    with (
        patch(
            "apps.agent.services.deerflow_adapter.family_adapter_cache._get_shared_checkpointer"
        ) as mock_get_ckpt,
        patch("apps.agent.services.session_store.AiSessionRepository") as MockRepo,
    ):
        checkpointer = mock_get_ckpt.return_value
        checkpointer.aget_tuple = AsyncMock(
            return_value=_checkpoint_with_title("新标题")
        )

        repo = MockRepo.return_value
        repo.get_session = AsyncMock(return_value={"title": "已有标题"})
        repo.update_summary = AsyncMock()

        await sync_title_from_checkpoint("thread-1", "family-1")

    repo.update_summary.assert_not_called()
