from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    # Auth
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_REFRESH_FAILED = "AUTH_REFRESH_FAILED"
    AUTH_RATE_LIMITED = "AUTH_RATE_LIMITED"
    AUTH_PIN_LOCKED = "AUTH_PIN_LOCKED"  # Child PIN lockout (423 Locked)
    AUTH_FAMILY_NOT_FOUND = "AUTH_FAMILY_NOT_FOUND"
    AUTH_INVITE_CODE_INVALID = "AUTH_INVITE_CODE_INVALID"
    AUTH_USERNAME_EXISTS = "AUTH_USERNAME_EXISTS"
    AUTH_PASSWORD_INCORRECT = "AUTH_PASSWORD_INCORRECT"
    AUTH_PASSWORD_SAME = "AUTH_PASSWORD_SAME"  # New password same as old
    AUTH_CHILD_NOT_FOUND = "AUTH_CHILD_NOT_FOUND"  # Child account not found
    AUTH_OWNER_ONLY = "AUTH_OWNER_ONLY"  # Owner-only operation required
    AUTH_NO_PASSKEY_REGISTERED = "AUTH_NO_PASSKEY_REGISTERED"
    AUTH_CREDENTIAL_NOT_FOUND = "AUTH_CREDENTIAL_NOT_FOUND"
    AUTH_WEBAUTHN_VERIFICATION_FAILED = "AUTH_WEBAUTHN_VERIFICATION_FAILED"
    AUTH_DEVICE_NOT_FOUND = "AUTH_DEVICE_NOT_FOUND"  # Device session not found or not owned by user

    # Family invitation code
    FAMILY_INVITATION_CODE_NOT_FOUND = "FAMILY_INVITATION_CODE_NOT_FOUND"
    FAMILY_INVITATION_CODE_ALREADY_USED = "FAMILY_INVITATION_CODE_ALREADY_USED"
    FAMILY_INVITATION_CODE_REVOKED = "FAMILY_INVITATION_CODE_REVOKED"

    # Captcha
    CAPTCHA_MISSING = "CAPTCHA_MISSING"
    CAPTCHA_INVALID = "CAPTCHA_INVALID"
    CAPTCHA_REPLAY = "CAPTCHA_REPLAY"
    CAPTCHA_SERVICE_UNAVAILABLE = "CAPTCHA_SERVICE_UNAVAILABLE"

    # Asset
    ASSET_NOT_FOUND = "ASSET_NOT_FOUND"
    ASSET_ALREADY_SOLD = "ASSET_ALREADY_SOLD"
    ASSET_FORBIDDEN = "ASSET_FORBIDDEN"

    # Liability
    LIABILITY_NOT_FOUND = "LIABILITY_NOT_FOUND"
    LIABILITY_FORBIDDEN = "LIABILITY_FORBIDDEN"
    LIABILITY_ALREADY_PAID = "LIABILITY_ALREADY_PAID"

    # Category
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
    CATEGORY_SYSTEM_READONLY = "CATEGORY_SYSTEM_READONLY"
    CATEGORY_FORBIDDEN = "CATEGORY_FORBIDDEN"

    # Tag
    TAG_NOT_FOUND = "TAG_NOT_FOUND"
    TAG_FORBIDDEN = "TAG_FORBIDDEN"

    # Family
    FAMILY_NOT_FOUND = "FAMILY_NOT_FOUND"
    FAMILY_FORBIDDEN = "FAMILY_FORBIDDEN"
    FAMILY_MEMBER_NOT_FOUND = "FAMILY_MEMBER_NOT_FOUND"
    FAMILY_NO_ACTIVE_MEMBERS = "FAMILY_NO_ACTIVE_MEMBERS"
    FAMILY_MEMBER_LIMIT_EXCEEDED = "FAMILY_MEMBER_LIMIT_EXCEEDED"  # Family member limit (50) exceeded

    # File
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_PATH_INVALID = "FILE_PATH_INVALID"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_FORMAT_INVALID = "FILE_FORMAT_INVALID"
    FILE_CONTENT_MISMATCH = "FILE_CONTENT_MISMATCH"

    # Storage
    STORAGE_RATE_LIMITED = "STORAGE_RATE_LIMITED"
    STORAGE_CONFLICT = "STORAGE_CONFLICT"
    STORAGE_CONNECTION_ERROR = "STORAGE_CONNECTION_ERROR"
    STORAGE_AUTH_ERROR = "STORAGE_AUTH_ERROR"
    STORAGE_ERROR = "STORAGE_ERROR"

    # AI
    AI_NOT_ENABLED = "AI_NOT_ENABLED"
    AI_SERVICE_UNAVAILABLE = "AI_SERVICE_UNAVAILABLE"
    AI_SERVICE_TIMEOUT = "AI_SERVICE_TIMEOUT"
    AI_CONFIG_MISSING_API_KEY = "AI_CONFIG_MISSING_API_KEY"
    AI_CONFIG_MISSING_PROVIDER = "AI_CONFIG_MISSING_PROVIDER"
    AI_SUGGESTION_NOT_FOUND = "AI_SUGGESTION_NOT_FOUND"
    AI_ALERT_NOT_FOUND = "AI_ALERT_NOT_FOUND"
    AI_DATA_WRITE_FAILED = "AI_DATA_WRITE_FAILED"
    AI_QUESTION_EMPTY = "AI_QUESTION_EMPTY"

    # Import
    IMPORT_PDF_UNREADABLE = "IMPORT_PDF_UNREADABLE"
    IMPORT_NO_ASSETS_FOUND = "IMPORT_NO_ASSETS_FOUND"
    IMPORT_AGENT_TIMEOUT = "IMPORT_AGENT_TIMEOUT"
    AI_SPENDING_LEAK_NOT_FOUND = "AI_SPENDING_LEAK_NOT_FOUND"
    AI_TASK_IN_PROGRESS = "AI_TASK_IN_PROGRESS"
    AI_REPORT_NOT_FOUND = "AI_REPORT_NOT_FOUND"
    AI_REPORT_MARKDOWN_NOT_FOUND = "AI_REPORT_MARKDOWN_NOT_FOUND"

    # Notification
    NOTIFICATION_NO_CHANNEL = "NOTIFICATION_NO_CHANNEL"

    # Currency
    EXCHANGE_RATE_NOT_FOUND = "EXCHANGE_RATE_NOT_FOUND"

    # Dashboard
    DASHBOARD_INVALID_STATUS = "DASHBOARD_INVALID_STATUS"

    # Rate limit
    RATE_LIMITED = "RATE_LIMITED"

    # Blind box
    BLIND_BOX_DISABLED = "BLIND_BOX_DISABLED"
    BLIND_BOX_INVALID_CHORE = "BLIND_BOX_INVALID_CHORE"
    BLIND_BOX_INSUFFICIENT_COINS = "BLIND_BOX_INSUFFICIENT_COINS"
    BLIND_BOX_GIFT_POOL_EMPTY = "BLIND_BOX_GIFT_POOL_EMPTY"
    BLIND_BOX_DRAW_NOT_FOUND = "BLIND_BOX_DRAW_NOT_FOUND"
    BLIND_BOX_BONUS_EXPIRED = "BLIND_BOX_BONUS_EXPIRED"
    BLIND_BOX_GIFT_NOT_FOUND = "BLIND_BOX_GIFT_NOT_FOUND"
    BLIND_BOX_WISH_CONFLICT = "BLIND_BOX_WISH_CONFLICT"

    # Literacy
    LITERACY_SCENARIO_COMPLETED = "LITERACY_SCENARIO_COMPLETED"
    LITERACY_REPORT_NOT_FOUND = "LITERACY_REPORT_NOT_FOUND"

    # Chore instance
    CHORE_INSTANCE_NOT_FOUND = "CHORE_INSTANCE_NOT_FOUND"
    CHORE_INSTANCE_STATUS_CONFLICT = "CHORE_INSTANCE_STATUS_CONFLICT"
    CHORE_ASSIGN_TARGET_INVALID = "CHORE_ASSIGN_TARGET_INVALID"
    CHORE_ALREADY_CLAIMED = "CHORE_ALREADY_CLAIMED"
    CHORE_NOT_YOURS = "CHORE_NOT_YOURS"

    # Calendar
    CALENDAR_DATE_INVALID = "CALENDAR_DATE_INVALID"
    CHILD_NOT_FOUND = "CHILD_NOT_FOUND"

    # General
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    FORBIDDEN = "FORBIDDEN"
    INTERNAL_ERROR = "INTERNAL_ERROR"


ERROR_META: dict[ErrorCode, int] = {
    ErrorCode.AUTH_INVALID_CREDENTIALS: 401,
    ErrorCode.AUTH_TOKEN_EXPIRED: 401,
    ErrorCode.AUTH_REFRESH_FAILED: 401,
    ErrorCode.AUTH_RATE_LIMITED: 429,
    ErrorCode.AUTH_PIN_LOCKED: 423,  # Child PIN lockout
    ErrorCode.AUTH_FAMILY_NOT_FOUND: 404,
    ErrorCode.AUTH_INVITE_CODE_INVALID: 404,
    ErrorCode.AUTH_USERNAME_EXISTS: 400,
    ErrorCode.AUTH_PASSWORD_INCORRECT: 400,
    ErrorCode.AUTH_PASSWORD_SAME: 400,
    ErrorCode.AUTH_CHILD_NOT_FOUND: 404,
    ErrorCode.AUTH_OWNER_ONLY: 403,
    ErrorCode.AUTH_NO_PASSKEY_REGISTERED: 400,
    ErrorCode.AUTH_CREDENTIAL_NOT_FOUND: 404,
    ErrorCode.AUTH_WEBAUTHN_VERIFICATION_FAILED: 401,
    ErrorCode.AUTH_DEVICE_NOT_FOUND: 404,
    ErrorCode.FAMILY_INVITATION_CODE_NOT_FOUND: 400,
    ErrorCode.FAMILY_INVITATION_CODE_ALREADY_USED: 400,
    ErrorCode.FAMILY_INVITATION_CODE_REVOKED: 400,
    ErrorCode.CAPTCHA_MISSING: 400,
    ErrorCode.CAPTCHA_INVALID: 400,
    ErrorCode.CAPTCHA_REPLAY: 400,
    ErrorCode.CAPTCHA_SERVICE_UNAVAILABLE: 503,
    ErrorCode.ASSET_NOT_FOUND: 404,
    ErrorCode.ASSET_ALREADY_SOLD: 400,
    ErrorCode.ASSET_FORBIDDEN: 403,
    ErrorCode.LIABILITY_NOT_FOUND: 404,
    ErrorCode.LIABILITY_FORBIDDEN: 403,
    ErrorCode.LIABILITY_ALREADY_PAID: 400,
    ErrorCode.CATEGORY_NOT_FOUND: 404,
    ErrorCode.CATEGORY_SYSTEM_READONLY: 403,
    ErrorCode.CATEGORY_FORBIDDEN: 403,
    ErrorCode.TAG_NOT_FOUND: 404,
    ErrorCode.TAG_FORBIDDEN: 403,
    ErrorCode.FAMILY_NOT_FOUND: 404,
    ErrorCode.FAMILY_FORBIDDEN: 403,
    ErrorCode.FAMILY_MEMBER_NOT_FOUND: 404,
    ErrorCode.FAMILY_NO_ACTIVE_MEMBERS: 404,
    ErrorCode.FAMILY_MEMBER_LIMIT_EXCEEDED: 400,
    ErrorCode.FILE_NOT_FOUND: 404,
    ErrorCode.FILE_PATH_INVALID: 500,
    ErrorCode.FILE_SIZE_EXCEEDED: 400,
    ErrorCode.FILE_FORMAT_INVALID: 400,
    ErrorCode.FILE_CONTENT_MISMATCH: 400,
    ErrorCode.STORAGE_RATE_LIMITED: 429,
    ErrorCode.STORAGE_CONFLICT: 409,
    ErrorCode.STORAGE_CONNECTION_ERROR: 503,
    ErrorCode.STORAGE_AUTH_ERROR: 401,
    ErrorCode.STORAGE_ERROR: 500,
    ErrorCode.AI_NOT_ENABLED: 403,
    ErrorCode.AI_SERVICE_UNAVAILABLE: 503,
    ErrorCode.AI_SERVICE_TIMEOUT: 504,
    ErrorCode.AI_CONFIG_MISSING_API_KEY: 400,
    ErrorCode.AI_CONFIG_MISSING_PROVIDER: 400,
    ErrorCode.AI_SUGGESTION_NOT_FOUND: 404,
    ErrorCode.AI_ALERT_NOT_FOUND: 404,
    ErrorCode.AI_DATA_WRITE_FAILED: 500,
    ErrorCode.AI_QUESTION_EMPTY: 422,
    ErrorCode.AI_SPENDING_LEAK_NOT_FOUND: 404,
    ErrorCode.AI_TASK_IN_PROGRESS: 409,
    ErrorCode.AI_REPORT_NOT_FOUND: 404,
    ErrorCode.AI_REPORT_MARKDOWN_NOT_FOUND: 404,
    ErrorCode.EXCHANGE_RATE_NOT_FOUND: 404,
    ErrorCode.DASHBOARD_INVALID_STATUS: 400,
    ErrorCode.RATE_LIMITED: 429,
    ErrorCode.VALIDATION_ERROR: 422,
    ErrorCode.NOT_FOUND: 404,
    ErrorCode.FORBIDDEN: 403,
    ErrorCode.INTERNAL_ERROR: 500,
    ErrorCode.BLIND_BOX_DISABLED: 403,
    ErrorCode.BLIND_BOX_INVALID_CHORE: 400,
    ErrorCode.BLIND_BOX_INSUFFICIENT_COINS: 400,
    ErrorCode.BLIND_BOX_GIFT_POOL_EMPTY: 404,
    ErrorCode.BLIND_BOX_DRAW_NOT_FOUND: 404,
    ErrorCode.BLIND_BOX_BONUS_EXPIRED: 410,
    ErrorCode.BLIND_BOX_GIFT_NOT_FOUND: 404,
    ErrorCode.BLIND_BOX_WISH_CONFLICT: 409,
    ErrorCode.LITERACY_SCENARIO_COMPLETED: 409,
    ErrorCode.LITERACY_REPORT_NOT_FOUND: 404,
    ErrorCode.CHORE_INSTANCE_NOT_FOUND: 404,
    ErrorCode.CHORE_INSTANCE_STATUS_CONFLICT: 409,
    ErrorCode.CHORE_ASSIGN_TARGET_INVALID: 403,
    ErrorCode.CHORE_ALREADY_CLAIMED: 409,
    ErrorCode.CHORE_NOT_YOURS: 404,
    ErrorCode.CALENDAR_DATE_INVALID: 422,
    ErrorCode.CHILD_NOT_FOUND: 404,
    ErrorCode.IMPORT_PDF_UNREADABLE: 400,
    ErrorCode.IMPORT_NO_ASSETS_FOUND: 422,
    ErrorCode.IMPORT_AGENT_TIMEOUT: 504,
    ErrorCode.NOTIFICATION_NO_CHANNEL: 422,
}
