"""add thread_id to literacy_weekly_reports

Revision ID: 2c22be59d705
Revises: 97d491c0b317
Create Date: 2026-07-29 11:37:48.060717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c22be59d705'
down_revision: Union[str, None] = '97d491c0b317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add thread_id column to literacy_weekly_reports table
    op.add_column('literacy_weekly_reports', sa.Column('thread_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_literacy_weekly_reports_thread_id'), 'literacy_weekly_reports', ['thread_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove thread_id column from literacy_weekly_reports table
    op.drop_index(op.f('ix_literacy_weekly_reports_thread_id'), table_name='literacy_weekly_reports')
    op.drop_column('literacy_weekly_reports', 'thread_id')
    # ### end Alembic commands ###