"""add family_settings and user_settings tables

Revision ID: 5c29147d17e4
Revises: d70b7f8bf50b
Create Date: 2026-07-28 12:59:46.032982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5c29147d17e4'
down_revision: Union[str, None] = 'd70b7f8bf50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_settings',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('family_id', sa.BigInteger(), nullable=False),
        sa.Column('key', sa.String(length=100), nullable=False),
        sa.Column('value', sa.String(length=500), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('family_id', 'key', name='uq_family_setting_family_key')
    )
    op.create_index(op.f('ix_family_settings_family_id'), 'family_settings', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_settings_family_key'), 'family_settings', ['family_id', 'key'], unique=False)

    op.create_table('user_settings',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('key', sa.String(length=100), nullable=False),
        sa.Column('value', sa.String(length=500), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'key', name='uq_user_setting_user_key')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_settings_user_key'), 'user_settings', ['user_id', 'key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_user_key'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_family_settings_family_key'), table_name='family_settings')
    op.drop_index(op.f('ix_family_settings_family_id'), table_name='family_settings')
    op.drop_table('family_settings')
    # ### end Alembic commands ###
