"""add device_sessions table

Revision ID: aa10837ae378
Revises: 98c68a46add7
Create Date: 2026-04-25 10:50:34.686932

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'aa10837ae378'
down_revision: str | None = '98c68a46add7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration was autogenerated on 2026-04-25 to convert the schema from
    # VARCHAR(36) UUID primary/foreign keys to BigInteger Snowflake IDs, AND to
    # drop a batch of legacy pre-Alembic tables (cached_files, ai_chat_sessions,
    # revoked_tokens, etc.).
    #
    # On a fresh database the base revision `e3cba86157fd` (initial_snowflake_schema)
    # already creates every table with BigInteger Snowflake IDs, and the legacy
    # tables were never created. So on a fresh DB this migration's drops and
    # alter_column calls are all no-ops — but bare op.drop_index would raise
    # "no such index" and op.alter_column would emit `ALTER COLUMN ... TYPE`
    # which SQLite does not support. Guard everything so the migration is
    # idempotent on both legacy (UUID) and fresh (Snowflake) databases.
    bind = op.get_bind()

    def _has_table(name: str) -> bool:
        return bind.dialect.has_table(bind, name)

    def _drop_table(name: str) -> None:
        if _has_table(name):
            op.drop_table(name)

    def _drop_index(index_name: str, table_name: str, **kwargs) -> None:
        # An index cannot exist without its table; skip when the table is gone.
        if not _has_table(table_name):
            return
        op.drop_index(op.f(index_name), table_name=table_name, **kwargs)

    def _is_snowflake() -> bool:
        # On a fresh DB the `users.id` column is already BIGINT (Snowflake).
        # When that's the case the UUID→BigInteger alter_column block below is a
        # no-op and must be skipped (SQLite rejects `ALTER COLUMN ... TYPE`).
        if not _has_table('users'):
            return False
        for col in bind.dialect.get_columns(bind, 'users'):
            if col['name'] == 'id':
                return 'BIGINT' in str(col['type']).upper() or 'INTEGER' in str(col['type']).upper()
        return False

    already_snowflake = _is_snowflake()

    op.create_table('device_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('family_id', sa.BigInteger(), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=False),
    sa.Column('refresh_jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_jti')
    )
    op.create_index('ix_device_sessions_family', 'device_sessions', ['family_id'], unique=False)
    op.create_index('ix_device_sessions_user_active', 'device_sessions', ['user_id', 'is_revoked', 'expires_at'], unique=False)
    # On a fresh (already-Snowflake) DB there are no legacy pre-Alembic tables to
    # drop and no UUID columns to alter — the drops below would delete tables
    # that the bootstrap (b00t5trap0001) just created from the current models.
    # Skip the entire legacy-cleanup + UUID→BigInteger block on fresh DBs.
    if already_snowflake:
        return
    _drop_index('ix_cached_files_family_id', table_name='cached_files')
    _drop_table('cached_files')
    _drop_index('ix_ai_chat_sessions_family_id', table_name='ai_chat_sessions')
    _drop_table('ai_chat_sessions')
    _drop_table('child_milestones')
    _drop_table('currencies')
    _drop_table('bonus_draws')
    _drop_table('coin_transactions')
    _drop_table('chore_instances')
    _drop_table('exchange_rates')
    _drop_index('ix_ai_allocation_targets_family_id', table_name='ai_allocation_targets')
    _drop_table('ai_allocation_targets')
    _drop_index('ix_ai_disposal_suggestions_family_id', table_name='ai_disposal_suggestions')
    _drop_table('ai_disposal_suggestions')
    _drop_index('ix_file_remote_locations_backend_status', table_name='file_remote_locations')
    _drop_index('ix_file_remote_locations_file_id', table_name='file_remote_locations')
    _drop_table('file_remote_locations')
    _drop_index('ix_security_audit_logs_created_at', table_name='security_audit_logs')
    _drop_index('ix_security_audit_logs_event_type', table_name='security_audit_logs')
    _drop_index('ix_security_audit_logs_family_id', table_name='security_audit_logs')
    _drop_index('ix_security_audit_logs_user_id', table_name='security_audit_logs')
    _drop_table('security_audit_logs')
    _drop_table('chore_templates')
    _drop_table('_schema_migration_lock')
    _drop_index('ix_ai_asset_alerts_family_id', table_name='ai_asset_alerts')
    _drop_table('ai_asset_alerts')
    _drop_table('blind_box_draws')
    _drop_table('chore_template_assignees')
    _drop_index('ix_ai_reports_family_id', table_name='ai_reports')
    _drop_table('ai_reports')
    _drop_table('storage_backends')
    _drop_table('activities')
    _drop_index('ix_sync_events_backend_occurred', table_name='sync_events')
    _drop_index('ix_sync_events_file_id', table_name='sync_events')
    _drop_table('sync_events')
    _drop_table('blind_box_config')
    _drop_index('ix_ai_chat_messages_family_id', table_name='ai_chat_messages')
    _drop_table('ai_chat_messages')
    _drop_table('blind_box_gifts')
    _drop_index('ix_revoked_tokens_expires_at', table_name='revoked_tokens')
    _drop_index('ix_revoked_tokens_jti', table_name='revoked_tokens')
    _drop_index('ix_revoked_tokens_user_expires', table_name='revoked_tokens')
    _drop_index('ix_revoked_tokens_user_id', table_name='revoked_tokens')
    _drop_table('revoked_tokens')
    # The alter_column block below converts VARCHAR(36) UUID columns to
    # BigInteger Snowflake IDs. On a fresh DB (initial_snowflake_schema) those
    # columns are already BIGINT, so the block is a no-op and must be skipped —
    # SQLite does not support `ALTER COLUMN ... TYPE`, and even on Postgres the
    # idempotent re-alter is wasteful. Legacy UUID databases still run it.
    # (Already returned above when already_snowflake — drops also skipped there.)
    op.alter_column('ai_ws_tickets', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('ai_ws_tickets', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('ai_ws_tickets', 'family_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('asset_snapshots', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('asset_snapshots', 'family_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('asset_snapshots', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('asset_tags', 'asset_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('asset_tags', 'tag_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('asset_valuations', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('asset_valuations', 'asset_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('assets', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('assets', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('assets', 'family_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('assets', 'category_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    _drop_index('ix_assets_family_id_is_archived', table_name='assets')
    _drop_index('ix_assets_family_id_status', table_name='assets')
    op.alter_column('categories', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('categories', 'family_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('child_bind_tokens', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('child_bind_tokens', 'family_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('child_wishes', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('child_wishes', 'family_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('child_wishes', 'child_user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('child_wishes', 'realized_asset_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('families', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('families', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('families', 'ai_provider',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('liabilities', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('liabilities', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('liabilities', 'family_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('liabilities', 'linked_asset_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('liabilities', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'CNY'"))
    _drop_index('ix_liabilities_family_id_is_active', table_name='liabilities')
    op.alter_column('payment_records', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payment_records', 'liability_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('tags', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('tags', 'family_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('users', 'family_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('users', 'theme',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'light'"))
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'zh-CN'"))
    op.alter_column('users', 'default_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'CNY'"))
    op.alter_column('users', 'view_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'card'"))
    _drop_index('ix_users_username_unique', table_name='users', sqlite_where=sa.text('username IS NOT NULL'))
    op.alter_column('wishes', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('wishes', 'family_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('wishes', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('wishes', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('wishes', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('wishes', 'category_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('wishes', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'CNY'"))
    op.alter_column('wishes', 'realized_asset_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishes', 'realized_asset_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('wishes', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'CNY'"))
    op.alter_column('wishes', 'category_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('wishes', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('wishes', 'priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'"))
    op.alter_column('wishes', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('wishes', 'family_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('wishes', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.create_index(op.f('ix_users_username_unique'), 'users', ['username'], unique=1, sqlite_where=sa.text('username IS NOT NULL'))
    op.alter_column('users', 'view_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'card'"))
    op.alter_column('users', 'default_currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'CNY'"))
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'zh-CN'"))
    op.alter_column('users', 'theme',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'light'"))
    op.alter_column('users', 'family_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('tags', 'family_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('tags', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('payment_records', 'liability_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('payment_records', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.create_index(op.f('ix_liabilities_family_id_is_active'), 'liabilities', ['family_id', 'is_active'], unique=False)
    op.alter_column('liabilities', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'CNY'"))
    op.alter_column('liabilities', 'linked_asset_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('liabilities', 'family_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('liabilities', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('liabilities', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('families', 'ai_provider',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('families', 'created_by',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('families', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('child_wishes', 'realized_asset_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('child_wishes', 'child_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('child_wishes', 'family_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('child_wishes', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('child_bind_tokens', 'family_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('child_bind_tokens', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('categories', 'family_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('categories', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.create_index(op.f('ix_assets_family_id_status'), 'assets', ['family_id', 'status'], unique=False)
    op.create_index(op.f('ix_assets_family_id_is_archived'), 'assets', ['family_id', 'is_archived'], unique=False)
    op.alter_column('assets', 'category_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('assets', 'family_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('assets', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('assets', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('asset_valuations', 'asset_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('asset_valuations', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('asset_tags', 'tag_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('asset_tags', 'asset_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('asset_snapshots', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('asset_snapshots', 'family_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('asset_snapshots', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('ai_ws_tickets', 'family_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('ai_ws_tickets', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('ai_ws_tickets', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jti', sa.VARCHAR(length=36), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('revoked_at', sa.FLOAT(), nullable=False),
    sa.Column('expires_at', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_user_id'), 'revoked_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_user_expires'), 'revoked_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=1)
    op.create_index(op.f('ix_revoked_tokens_expires_at'), 'revoked_tokens', ['expires_at'], unique=False)
    op.create_table('blind_box_gifts',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('emoji', sa.VARCHAR(length=10), nullable=True),
    sa.Column('value_score', sa.INTEGER(), nullable=False),
    sa.Column('source_wish_id', sa.BIGINT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['source_wish_id'], ['child_wishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=10), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_messages_family_id'), 'ai_chat_messages', ['family_id'], unique=False)
    op.create_table('blind_box_config',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('base_draw_prob', sa.FLOAT(), server_default=sa.text('(0.30)'), nullable=False),
    sa.Column('special_day_prob', sa.FLOAT(), server_default=sa.text('(0.80)'), nullable=False),
    sa.Column('weight_scale', sa.FLOAT(), server_default=sa.text('(2.0)'), nullable=False),
    sa.Column('surprise_threshold_coins', sa.INTEGER(), server_default=sa.text('(200)'), nullable=False),
    sa.Column('surprise_prob_normal', sa.FLOAT(), server_default=sa.text('(0.05)'), nullable=False),
    sa.Column('surprise_prob_parent_bday', sa.FLOAT(), server_default=sa.text('(0.60)'), nullable=False),
    sa.Column('surprise_prob_sibling_bday', sa.FLOAT(), server_default=sa.text('(0.50)'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', name=op.f('uq_blind_box_config_family'))
    )
    op.create_table('sync_events',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('file_id', sa.BIGINT(), nullable=False),
    sa.Column('backend_id', sa.BIGINT(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('detail', sa.TEXT(), nullable=True),
    sa.Column('occurred_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['backend_id'], ['storage_backends.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['cached_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_events_file_id'), 'sync_events', ['file_id'], unique=False)
    op.create_index(op.f('ix_sync_events_backend_occurred'), 'sync_events', ['backend_id', 'occurred_at'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('entity_id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_backends',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('backend_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('config', sa.TEXT(), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_reports',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('report_json', sqlite.JSON(), nullable=False),
    sa.Column('overall_score', sa.INTEGER(), nullable=True),
    sa.Column('data_completeness_score', sa.FLOAT(), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reports_family_id'), 'ai_reports', ['family_id'], unique=False)
    op.create_table('chore_template_assignees',
    sa.Column('template_id', sa.BIGINT(), nullable=False),
    sa.Column('child_user_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['child_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['chore_templates.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'child_user_id')
    )
    op.create_table('blind_box_draws',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('child_user_id', sa.BIGINT(), nullable=False),
    sa.Column('coins_spent', sa.INTEGER(), nullable=False),
    sa.Column('gift_id', sa.BIGINT(), nullable=False),
    sa.Column('is_surprise', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_bonus', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('source_wish_id', sa.BIGINT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'pending_fulfillment'"), nullable=False),
    sa.Column('draw_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fulfilled_at', sa.DATETIME(), nullable=True),
    sa.CheckConstraint("status IN ('pending_fulfillment', 'fulfilled')", name=op.f('ck_blind_box_draw_status')),
    sa.ForeignKeyConstraint(['child_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['gift_id'], ['blind_box_gifts.id'], ),
    sa.ForeignKeyConstraint(['source_wish_id'], ['child_wishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_asset_alerts',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('asset_id', sa.BIGINT(), nullable=False),
    sa.Column('asset_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=False),
    sa.Column('suggestion', sa.TEXT(), nullable=True),
    sa.Column('remaining_life_days', sa.INTEGER(), nullable=True),
    sa.Column('daily_cost', sa.FLOAT(), nullable=True),
    sa.Column('is_dismissed', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('dismissed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_asset_alerts_family_id'), 'ai_asset_alerts', ['family_id'], unique=False)
    op.create_table('_schema_migration_lock',
    sa.Column('lock_id', sa.TEXT(), nullable=True),
    sa.Column('locked_at', sa.REAL(), nullable=True),
    sa.Column('holder', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('lock_id')
    )
    op.create_table('chore_templates',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=10), nullable=True),
    sa.Column('coin_reward', sa.INTEGER(), nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('assignment_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_audit_logs',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('family_id', sa.BIGINT(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=512), nullable=True),
    sa.Column('outcome', sa.VARCHAR(length=16), nullable=False),
    sa.Column('detail', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_logs_user_id'), 'security_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_family_id'), 'security_audit_logs', ['family_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_event_type'), 'security_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_created_at'), 'security_audit_logs', ['created_at'], unique=False)
    op.create_table('file_remote_locations',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('file_id', sa.BIGINT(), nullable=False),
    sa.Column('backend_id', sa.BIGINT(), nullable=False),
    sa.Column('remote_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('remote_url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('remote_sha', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('synced_at', sa.DATETIME(), nullable=True),
    sa.Column('last_error', sa.TEXT(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['backend_id'], ['storage_backends.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['cached_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'backend_id', name=op.f('uq_file_remote_locations_file_backend'))
    )
    op.create_index(op.f('ix_file_remote_locations_file_id'), 'file_remote_locations', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_remote_locations_backend_status'), 'file_remote_locations', ['backend_id', 'sync_status'], unique=False)
    op.create_table('ai_disposal_suggestions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('asset_id', sa.BIGINT(), nullable=False),
    sa.Column('asset_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('inefficiency_score', sa.INTEGER(), nullable=False),
    sa.Column('suggested_channel', sa.VARCHAR(length=100), nullable=True),
    sa.Column('estimated_resale_range', sa.VARCHAR(length=100), nullable=True),
    sa.Column('suggestion', sa.TEXT(), nullable=True),
    sa.Column('daily_cost', sa.FLOAT(), nullable=True),
    sa.Column('is_dismissed', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('dismissed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_disposal_suggestions_family_id'), 'ai_disposal_suggestions', ['family_id'], unique=False)
    op.create_table('ai_allocation_targets',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('category_targets', sqlite.JSON(), nullable=False),
    sa.Column('drift_threshold', sa.FLOAT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_allocation_targets_family_id'), 'ai_allocation_targets', ['family_id'], unique=1)
    op.create_table('exchange_rates',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('base_currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('target_currency', sa.VARCHAR(length=10), nullable=False),
    sa.Column('rate', sa.FLOAT(), nullable=False),
    sa.Column('fetched_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_currency', 'fetched_at')
    )
    op.create_table('chore_instances',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('template_id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('child_user_id', sa.BIGINT(), nullable=False),
    sa.Column('chore_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('chore_emoji', sa.VARCHAR(length=10), nullable=True),
    sa.Column('coin_reward', sa.INTEGER(), nullable=False),
    sa.Column('date_bucket', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('streak_count', sa.INTEGER(), nullable=False),
    sa.Column('streak_bonus', sa.INTEGER(), nullable=False),
    sa.Column('submitted_by_user_id', sa.BIGINT(), nullable=True),
    sa.Column('consumed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['child_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['chore_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'child_user_id', 'date_bucket', name=op.f('uq_chore_instance'))
    )
    op.create_table('coin_transactions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('child_user_id', sa.BIGINT(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ref_id', sa.BIGINT(), nullable=True),
    sa.Column('narrative', sa.TEXT(), nullable=True),
    sa.Column('narrative_emoji', sa.VARCHAR(length=20), nullable=True),
    sa.Column('streak_bonus', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['child_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_id', 'transaction_type', name=op.f('uq_coin_tx_ref_type'))
    )
    op.create_table('bonus_draws',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('child_user_id', sa.BIGINT(), nullable=False),
    sa.Column('source_wish_id', sa.BIGINT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'available'"), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used_draw_id', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'used', 'expired')", name=op.f('ck_bonus_draw_status')),
    sa.ForeignKeyConstraint(['child_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['source_wish_id'], ['child_wishes.id'], ),
    sa.ForeignKeyConstraint(['used_draw_id'], ['blind_box_draws.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name_zh', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name_en', sa.VARCHAR(length=50), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=False),
    sa.Column('flag_emoji', sa.VARCHAR(length=10), nullable=False),
    sa.Column('is_favorite', sa.BOOLEAN(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('child_milestones',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('child_user_id', sa.BIGINT(), nullable=False),
    sa.Column('milestone_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('triggered_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ref_id', sa.BIGINT(), nullable=True),
    sa.Column('ref_type', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['child_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_chat_sessions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('cached_file_id', sa.BIGINT(), nullable=True),
    sa.Column('jsonl_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('message_count', sa.INTEGER(), nullable=False),
    sa.Column('last_preview', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['cached_file_id'], ['cached_files.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_sessions_family_id'), 'ai_chat_sessions', ['family_id'], unique=False)
    op.create_table('cached_files',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('family_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('sha256', sa.VARCHAR(length=64), nullable=False),
    sa.Column('local_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('size_bytes', sa.INTEGER(), nullable=False),
    sa.Column('date_dir', sa.VARCHAR(length=8), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', 'family_id', name=op.f('uq_cached_files_sha256_family'))
    )
    op.create_index(op.f('ix_cached_files_family_id'), 'cached_files', ['family_id'], unique=False)
    op.drop_index('ix_device_sessions_user_active', table_name='device_sessions')
    op.drop_index('ix_device_sessions_family', table_name='device_sessions')
    op.drop_table('device_sessions')
    # ### end Alembic commands ###