from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    # Auth
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_REFRESH_FAILED = "AUTH_REFRESH_FAILED"
    AUTH_RATE_LIMITED = "AUTH_RATE_LIMITED"
    AUTH_FAMILY_NOT_FOUND = "AUTH_FAMILY_NOT_FOUND"
    AUTH_INVITE_CODE_INVALID = "AUTH_INVITE_CODE_INVALID"
    AUTH_USERNAME_EXISTS = "AUTH_USERNAME_EXISTS"

    # Asset
    ASSET_NOT_FOUND = "ASSET_NOT_FOUND"
    ASSET_ALREADY_SOLD = "ASSET_ALREADY_SOLD"
    ASSET_FORBIDDEN = "ASSET_FORBIDDEN"

    # Liability
    LIABILITY_NOT_FOUND = "LIABILITY_NOT_FOUND"
    LIABILITY_FORBIDDEN = "LIABILITY_FORBIDDEN"
    LIABILITY_ALREADY_PAID = "LIABILITY_ALREADY_PAID"

    # Category
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
    CATEGORY_SYSTEM_READONLY = "CATEGORY_SYSTEM_READONLY"
    CATEGORY_FORBIDDEN = "CATEGORY_FORBIDDEN"

    # Tag
    TAG_NOT_FOUND = "TAG_NOT_FOUND"
    TAG_FORBIDDEN = "TAG_FORBIDDEN"

    # Family
    FAMILY_NOT_FOUND = "FAMILY_NOT_FOUND"
    FAMILY_FORBIDDEN = "FAMILY_FORBIDDEN"
    FAMILY_MEMBER_NOT_FOUND = "FAMILY_MEMBER_NOT_FOUND"
    FAMILY_NO_ACTIVE_MEMBERS = "FAMILY_NO_ACTIVE_MEMBERS"

    # File
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_PATH_INVALID = "FILE_PATH_INVALID"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_FORMAT_INVALID = "FILE_FORMAT_INVALID"
    FILE_CONTENT_MISMATCH = "FILE_CONTENT_MISMATCH"

    # Storage
    STORAGE_RATE_LIMITED = "STORAGE_RATE_LIMITED"
    STORAGE_CONFLICT = "STORAGE_CONFLICT"
    STORAGE_CONNECTION_ERROR = "STORAGE_CONNECTION_ERROR"
    STORAGE_AUTH_ERROR = "STORAGE_AUTH_ERROR"
    STORAGE_ERROR = "STORAGE_ERROR"

    # AI
    AI_SERVICE_UNAVAILABLE = "AI_SERVICE_UNAVAILABLE"
    AI_SERVICE_TIMEOUT = "AI_SERVICE_TIMEOUT"
    AI_CONFIG_MISSING_API_KEY = "AI_CONFIG_MISSING_API_KEY"
    AI_CONFIG_MISSING_PROVIDER = "AI_CONFIG_MISSING_PROVIDER"
    AI_SUGGESTION_NOT_FOUND = "AI_SUGGESTION_NOT_FOUND"
    AI_ALERT_NOT_FOUND = "AI_ALERT_NOT_FOUND"
    AI_DATA_WRITE_FAILED = "AI_DATA_WRITE_FAILED"
    AI_QUESTION_EMPTY = "AI_QUESTION_EMPTY"

    # Currency
    EXCHANGE_RATE_NOT_FOUND = "EXCHANGE_RATE_NOT_FOUND"

    # Rate limit
    RATE_LIMITED = "RATE_LIMITED"

    # General
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    FORBIDDEN = "FORBIDDEN"
    INTERNAL_ERROR = "INTERNAL_ERROR"


ERROR_META: dict[ErrorCode, int] = {
    ErrorCode.AUTH_INVALID_CREDENTIALS: 401,
    ErrorCode.AUTH_TOKEN_EXPIRED: 401,
    ErrorCode.AUTH_REFRESH_FAILED: 401,
    ErrorCode.AUTH_RATE_LIMITED: 429,
    ErrorCode.AUTH_FAMILY_NOT_FOUND: 404,
    ErrorCode.AUTH_INVITE_CODE_INVALID: 404,
    ErrorCode.AUTH_USERNAME_EXISTS: 400,
    ErrorCode.ASSET_NOT_FOUND: 404,
    ErrorCode.ASSET_ALREADY_SOLD: 400,
    ErrorCode.ASSET_FORBIDDEN: 403,
    ErrorCode.LIABILITY_NOT_FOUND: 404,
    ErrorCode.LIABILITY_FORBIDDEN: 403,
    ErrorCode.LIABILITY_ALREADY_PAID: 400,
    ErrorCode.CATEGORY_NOT_FOUND: 404,
    ErrorCode.CATEGORY_SYSTEM_READONLY: 403,
    ErrorCode.CATEGORY_FORBIDDEN: 403,
    ErrorCode.TAG_NOT_FOUND: 404,
    ErrorCode.TAG_FORBIDDEN: 403,
    ErrorCode.FAMILY_NOT_FOUND: 404,
    ErrorCode.FAMILY_FORBIDDEN: 403,
    ErrorCode.FAMILY_MEMBER_NOT_FOUND: 404,
    ErrorCode.FAMILY_NO_ACTIVE_MEMBERS: 404,
    ErrorCode.FILE_NOT_FOUND: 404,
    ErrorCode.FILE_PATH_INVALID: 500,
    ErrorCode.FILE_SIZE_EXCEEDED: 400,
    ErrorCode.FILE_FORMAT_INVALID: 400,
    ErrorCode.FILE_CONTENT_MISMATCH: 400,
    ErrorCode.STORAGE_RATE_LIMITED: 429,
    ErrorCode.STORAGE_CONFLICT: 409,
    ErrorCode.STORAGE_CONNECTION_ERROR: 503,
    ErrorCode.STORAGE_AUTH_ERROR: 401,
    ErrorCode.STORAGE_ERROR: 500,
    ErrorCode.AI_SERVICE_UNAVAILABLE: 503,
    ErrorCode.AI_SERVICE_TIMEOUT: 504,
    ErrorCode.AI_CONFIG_MISSING_API_KEY: 400,
    ErrorCode.AI_CONFIG_MISSING_PROVIDER: 400,
    ErrorCode.AI_SUGGESTION_NOT_FOUND: 404,
    ErrorCode.AI_ALERT_NOT_FOUND: 404,
    ErrorCode.AI_DATA_WRITE_FAILED: 500,
    ErrorCode.AI_QUESTION_EMPTY: 422,
    ErrorCode.EXCHANGE_RATE_NOT_FOUND: 404,
    ErrorCode.RATE_LIMITED: 429,
    ErrorCode.VALIDATION_ERROR: 422,
    ErrorCode.NOT_FOUND: 404,
    ErrorCode.FORBIDDEN: 403,
    ErrorCode.INTERNAL_ERROR: 500,
}
